from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
import os
from fastapi.middleware.cors import CORSMiddleware
from fastapi import FastAPI
import hashlib
from datetime import datetime

app = FastAPI()
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # allow all origins (safe for demo)
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
@app.get("/")
def home():
    return {"message": "AutoJustice AI Backend Running"}

@app.post("/detect-attack")
def detect_attack(failed_attempts: int):
    if failed_attempts >= 5:
        return {
            "attack_type": "Brute Force",
            "severity": "High"
        }
    else:
        return {
            "attack_type": "Normal Activity",
            "severity": "Low"
        }
@app.get("/map-law")
def map_law(attack_type: str):
    if attack_type == "Brute Force":
        return {
            "laws": [
                "IT Act 2000 – Section 43",
                "IT Act 2000 – Section 66C",
                "GDPR – Article 32"
            ],
            "crime_type": "Unauthorized System Access"
        }
    return {"laws": [], "crime_type": "None"}
@app.get("/generate-evidence")
def generate_evidence(log_data: str):
    hash_value = hashlib.sha256(log_data.encode()).hexdigest()
    return {
        "hash": hash_value,
        "timestamp": datetime.now().strftime("%d-%m-%Y %H:%M:%S"),
        "integrity": "Verified",
        "chain_of_custody": "Maintained"
    }
@app.get("/risk-score")
def risk_score(severity: str):
    if severity == "High":
        return {
            "risk_score": "91%",
            "status": "CRITICAL",
            "estimated_fine": "₹75,00,000"
        }
    return {
        "risk_score": "10%",
        "status": "LOW",
        "estimated_fine": "₹0"
    }
@app.get("/generate-case")
def generate_case():
    return {
        "case_id": "AJ-2025-001",
        "attack": "Brute Force",
        "laws": ["IT Act 43", "IT Act 66C", "GDPR 32"],
        "risk": "CRITICAL",
        "status": "Case File Generated"
    }
@app.get("/generate-pdf")
def generate_pdf():
    file_name = "AutoJustice_FIR_Report.pdf"
    file_path = os.path.join(os.getcwd(), file_name)

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, height - 50, "AUTOJUSTICE AI – FIR REPORT")

    c.setFont("Helvetica", 12)
    c.drawString(50, height - 100, "Case ID: AJ-2025-001")
    c.drawString(50, height - 130, "Incident Type: Brute Force Attack")
    c.drawString(50, height - 160, "Severity: HIGH")
    c.drawString(50, height - 190, "Violated Laws:")
    c.drawString(70, height - 220, "- IT Act 2000 – Section 43")
    c.drawString(70, height - 250, "- IT Act 2000 – Section 66C")
    c.drawString(70, height - 280, "- GDPR – Article 32")

    c.drawString(50, height - 320, "Digital Evidence:")
    c.drawString(70, height - 350, "SHA-256 Hash Generated")
    c.drawString(70, height - 380, "Timestamp Verified")
    c.drawString(70, height - 410, "Chain of Custody Maintained")

    c.drawString(50, height - 460, "Risk Assessment:")
    c.drawString(70, height - 490, "Risk Score: 91% (CRITICAL)")
    c.drawString(70, height - 520, "Estimated Regulatory Fine: ₹75,00,000")

    c.drawString(50, height - 580, "Status: Auto-generated by AutoJustice AI")

    c.save()

    return {
        "message": "PDF report generated successfully",
        "file": file_name
    }

